# NumPy Correlation Calculation

#  Create an array x of integers between 10 (inclusive) and 20 (exclusive). Use np.arange()

In [2]:
import numpy as np
import pandas as pd
from scipy import stats

In [3]:
x = np.arange(10,20)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

# Then use np.array() to create a second array y containing 10 arbitrary integers.

In [4]:
y = np.array([1,3,4,4,6,8,9,10,7,7])
y

array([ 1,  3,  4,  4,  6,  8,  9, 10,  7,  7])

# Once you have two arrays of the same length, you can compute the **correlation coefficient** between x and y

In [5]:
r = np.corrcoef(x,y)
r

array([[1.        , 0.83170436],
       [0.83170436, 1.        ]])